### ISSUE TITLE
contiguous_container::emplace always requires 2 move or 2 copy constructions

### ISSUE THREAD

**Issue by gnzlbg** [everard/contiguous-container#1]
It should require only one in most cases (e.g. most std::allocator implementations use placement new to construct the element in place).

**Comment by everard** [comment]
hm, there is only one move or copy, actually. One construction, one move/copy and one destruction of moved-from.

**Comment by gnzlbg** [comment]
Indeed, one construction (which might invoke an user defined constructor, a move or copy constructor), and then there is one move or copy construction, and the destruction. The last move/copy construction is what I think is not necessary.

**Comment by everard** [comment]
You mean, that it should be constructed in-place, after elements have been shifted? In this case there will be one destruction and one emplace construction, but if this last constructor throws, then there will be a hole in the container. GCC's std::vector implementation actually also moves from temporary variable for the same reason.

**Comment by gnzlbg** [comment]
I was thinking more like emplace at the end, and if that succeeds, swap the element one position at a time from the end to the desired position.

**Comment by everard** [comment]
Oh, I get it :)
Actually swap can be more expensive than just move. I think this is the logic that implementors of stdlib followed.

**Comment by gnzlbg** [comment]
Shifting all the elements should require swaps anyways, but I can check how libc++ does it. If they do it like GCC then that's the way to do it I guess.

**Comment by everard** [comment]
No, it requires move assignment, and move construction not swap

**Comment by everard** [comment]
This is how they do it:
```
value_type __tmp(_VSTD::forward<_Args>(__args)...);
__move_range(__p, this->__end_, __p + 1);
*__p = _VSTD::move(__tmp);
```
__p is a position

**Comment by gnzlbg** [comment]
It seems like they do it in a similar way.

**Comment by everard** [comment]
So I'm closing this?

**Comment by gnzlbg** [comment]
Yes, maybe it cannot be done how I had in mind, or it turns out to be slower, or involves more move assignments/copy assignments.
