### ISSUE TITLE
check_input_iterator is "unimplemented"

### ISSUE THREAD

**Issue by gnzlbg** [everard/contiguous-container#3]

**Comment by everard** [comment]
Please, elaborate

**Comment by everard** [comment]
Standard says that "The extent to which an implementation determines that a type cannot be an input iterator is unspecified, except that as a minimum integral types shall not qualify as input iterators."

**Comment by gnzlbg** [comment]
Indeed, my bad. This was the habit of constraining everything showing up.

**Comment by everard** [comment]
I can relate to that =)
