### ISSUE TITLE
Questions about storage_traits

### ISSUE THREAD

**Issue by gnzlbg** [everard/contiguous-container#5]
The following are my comments after reimplementing most of `storage_traits` (and `contiguous_container`) to build an `inline_vector<T, Capacity>` that is `constexpr` for literal types, and together with `variant` to build a `small_vector<T, N, A>` that is implemented as `variant<inline_vector<T, N>, std::vector<T, A>>`.

IIUC the objective of `storage_traits` is to factor out "optional" `Storage` functionality.

One can deal with the optional functionality within `contiguous_container`, so why is factoring this out into a trait class useful? Since `contiguous_container` imposes no overhead over the Storage, somebody wanting to reuse the `Storage` for "something else" can just reuse `contiguous_container<Storage>` instead.

In my opinion, the trait class unnecessarily complicates both the design and the proposal.

The only _really_ useful thing I think the trait class does is provide fallback implementations of `construct`/`destroy`/`reallocate`. However, I wonder if doing so silently in a trait class is the right place for these, since they are actually really important for the behavior of the storage. 

I would rather provide three helper classes instead, that users can use to build their own storage classes and provide the default behavior, but in an explicit way. For example: 

```c++
template <typename Storage>
struct with_placement_new_construct {
  using Storage::Storage;
  using Storage::operator=;

   template <typename... Args>
   constexpr pointer construct(pointer location, Args&&... args) {
     Storage const& s = static_cast<Storage const&>(*this);
     assert(location - s.data() >= 0);
     assert(location - s.data() <= s.capacity());
     ::new((void*)ptr_cast(location)) value_type{std::forward<Args>(args)...};
     return location;
    }
};
``` 

that can be explicitly opted into when declaring a new storage type: 

```c++
template <typename T>
struct my_storage : with_placement_new_construct<my_storage<T>> { ... };
```

It might get a bit verbose, to do the following:

```c++
template <typename T>
struct my_storage 
: with_placement_new_construct<my_storage<T>> 
, with_explicit_destructor_call<my_storage<T>>
, without_reallocate
{ ... };
```

but I think it makes things more clear.

Then, I wonder why `construct` and `destroy` need to be "customizable". 

Isn't the following enough, and can it just be part of `contiguous_storage`?

```c++
template <typename... Args>
constexpr pointer construct(pointer location, Args&&... args) {
  // assert(location - data() >= 0 and location - data() <= capacity());
  if constexpr(not is_trivially_constructible_v<value_type>) {
    ::new((void*)ptr_cast(location)) value_type{std::forward<Args>(args)...};
  }
  return location;
}

constexpr void destroy(pointer location) noexcept {
  if constexpr (not is_trivially_destructible_v<value_type>) {
    ptr_cast(location)->~value_type();
  }
}
```

In which situations would one need to customize `destroy`/`construct`?

Then I have some other minor comments:

- The traits allow the storage type to provide a begin/end/full/empty/... member functions, but these can always be implemented using `data()`, `size()`, and `capacity()`, why _allow_ the `Storage` to provide these? Which other behavior could be provided by the storage to warrant this?

- The `size` function returns a reference that allows `contiguous_storage` to "unsafely"/"directly" change the size of the underlying storage without "resizing" the container. Because the size is mutated through a reference, this does not allow a `Storage` implementation to e.g. `assert` that the size is within a valid range (e.g. in the `inline_vector` example, the `Storage` class might want to assert that the resulting size is smaller equal `capacity()` because the capacity is fixed).

**Comment by everard** [comment]
The storage_traits mimics allocator_traits. So the same reasoning behind customizing construct/destroy of an allocator. 
Regarding your minor comments:
1) For optimization reasons. For example, if there are three pointers, like in GCC's implementation of std::vector, then end() will be just returning a pointer instead of begin() + size().
2) There is no need to assert anything here, since contiguous_container will not increase size beyond capacity, neither it will decrease it below zero.

**Comment by gnzlbg** [comment]
> The storage_traits mimics allocator_traits.

Why? I am also missing from the proposal: why use a trait class (why not use free-functions and ADL, or the paper [N4381: Suggested Design for Customization points](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4381.html)), etc.

> For optimization reasons. For example, if there are three pointers, like in GCC's implementation of std::vector, then end() will be just returning a pointer instead of begin() + size().

I saw this mentioned in the introduction of the paper, but I guess it also belongs to the design rationale section. That would have made it more clear for me.

> There is no need to assert anything here, since contiguous_container will not increase size beyond capacity, neither it will decrease it below zero.

Is `Storage` only supposed to ever be usable with `contiguous_container` ? What about a `flat_map<Storage>` ? or `my_flat_set<Storage>` ? Do you promise that none of them will have a bug that will try to increase the size beyond capacity? I would still want to check this in my own `Storage` classes. 

EDIT: and from this I wonder whether `Storage` is reusable for anything else, or anybody that wants to reuse `Storage` should "reuse" `contiguous_vector<Storage>` instead.

**Comment by everard** [comment]
Ok, these are valid points, I agree. Is it usable for flat_map/set? The answer is I don't know.

**Comment by everard** [comment]
Also why am I using traits for this? Simply because Standard uses the same approach, or rather I'm doing the same thing as the Standard does with lots of its classes.

**Comment by gnzlbg** [comment]
I just think that `storage_traits` makes the proposal larger and more complicated/messier. Allocators are just messy, so maybe `Storage` is messy as well. In that case, there is nothing we can do about it, and we need a trait system. 

I would still just want it to be simplified as much as possible. For example:

- what is the relation between `pointer`, `const_pointer`, and `value_type`, does `Storage` need to provide these 3, or does one suffice? Is there a reason why `contiguous_container` or other containers cannot assume that `pointer == T*` ? If yes, the reason belongs to the rationale, otherwise, making `Storage` to provide only `value_type` simplifies things

- I understand the "optimization" argument behind allowing `Storage`'provided `being`, `end`, `empty`, `full`, `size`, `capacity`, `data`, ... but `data`, `size`, and `capacity` are enough to implement all these. While I understand that this allows more optimized implementations for different vector storages like "one pointer 2 indices" vs "3 pointers", they also increase the API surface of `storage_traits` _a lot_ (too much for my taste). My intuition tells me that the performance difference between an API that only requires `data/size/capacity` vs one that allows all of them to have optimized implementations will not be measurable. So I would really like to see benchmarks that show that this is necessary, because I don't think it is, and they complicates the proposal. 

- Thinking more about supporting other containers like `flat_map`, the current design will not work, because of the possible need to "rebind" the allocated type. For this, one would need to offer something akin to `Allocator::rebind`, so that a `custom_container` could:

```c++
template <typename T, typename Storage>
struct custom_container : Storage::rebind<node_type<T>> { 
  // the Storage inherited from custom container
  // stores node_type<T> instead of T
};
```

That would make `Storage` more similar to `Allocator` in some sense and I don't think this should be pursued, since those containers can be built by wrapping `contiguous_container<Storage<node_type<T>>` instead. 

The proposal should try to have a `vector_facade` that takes the simplest possible `Storage` description and transforms it into something as close to a vector as possible.

**Comment by everard** [comment]
1. value_type must always be defined in Storage.
The definition of pointer and const_pointer is the same as definition of similar types in allocator: if type is defined in Storage, then that type is used, otherwise default is used. The defaults are: T* for pointer, `pointer_traits<pointer>::rebind<const T>` for `const_pointer` (which is const T*).
The reason is the same as for other containers: user-defined pointer-like types.
This way we can define allocator-aware container using contiguous_container. If we don't do this, then we rule out people who want to use their own pointer-like types.

2. Who knows? Maybe on some low-power devices this makes a lot of difference. Why sacrifice performance for no reason? Simplifying storage_traits is not concern of users, because in most cases they will just use defaults, they won't even look at implementation. There will always be someone, who wants to apply optimizations, trust me =)

3. I didn't think about maps/sets at all, so can't reply to this one. Also there was a proposal draft that did just that: defined flat_map/set as container adaptors.


Oh, and about that mix-in classes that you defined in your first comment: they and storage_traits can coexist, actually. Since storage_traits will detect existence of construct, nothing stops us from providing standard mix-ins, which then users will use in their code, so I don't see any issues here.

**Comment by gnzlbg** [comment]
Currently it just seems to me that `Storage` types are only supposed to be used within `contiguous_container` (since using them for other containers seems like a bad idea). 

I still wonder why we need `storage_traits` at all:
- are users supposed to specialize `storage_traits`? This doesn't seem to be the case since everything is detected automatically. 
- are users supposed to use `storage_traits` for _anything_?

I mean, to me it just sound that `storage_traits` is an implementation detail of `contiguous_container`. None of your examples uses `storage_traits` for anything, so that doesn't help.

The main difference with respect to `Allocator`s is that `Allocator`s are supposed to be used both independently of containers, and while users implement their own containers. Adding `storage_traits` as part of the API without a good understanding of their uses cases in user code seems just too much risk for possibly no benefit.

EDIT: so.. why I guess I am missing from the proposal is, what can users use `storage_traits` for? Maybe show an example of how that could be used, or just yank it completely, at least until we come up with a good use case for it beyond implementing `contiguous_container`.

**Comment by everard** [comment]
Yes, they can use storage_traits. For example, they can use storage_traits::construct/destroy when implementing reallocate. And they can write their own specialization, just like for allocator_traits.

**Comment by everard** [comment]
Ok, I understand, but decoupling storage_traits from contiguous_container simplifies definition, because pointer/const_pointer, size_type/difference_type, construct/destroy is property of memory model, which is different concept from container.

**Comment by gnzlbg** [comment]
> Yes, they can use storage_traits. For example, they can use storage_traits::construct/destroy when implementing reallocate. And they can write their own specialization, just like for allocator_traits.

The proposal and the examples need to show why this is useful. While I can imagine that some generic construct/destruct implementations could be useful for implementing reallocate, I would like to see a particular example. It might be worth it to try to show what they need to be traits and cannot be just reusable free functions. Specialization is something you actually need the trait class for, but here I cannot even imagine a single use case :/

> Ok, I understand, but decoupling storage_traits from contiguous_container simplifies definition, because pointer/const_pointer, size_type/difference_type, construct/destroy is property of memory model, different concept from container

Storage is more like a container than like an Allocator (in fact some Storage like `dynamic_uninitialized_memory_buffer` could probably take an `Allocator` as template parameter and be implemented by calling the `Allocator`.

Anyhow I'll just wait for the examples. If it turns out that storage traits isn't really useful as its own standalone thing that doesn't mean that it cannot be used to implement `contiguous_container`. But for example, I would just have used SFINAE and overloading in the implementation of `contiguous_container` to implement the fallback behavior, instead of doing so in a trait class.

**Comment by everard** [comment]
I have to think about this. I kinda agree with you, that since we can't come up with good examples of usage of Storage beyond contiguous_container, then probably there is no need to define traits for it in specification.

**Comment by everard** [comment]
I thought about this issue. Traits are actually useful, because if you make Storage interface private/protected, then you'll have to declare each free function, which implements fallback functionality, to be friend of Storage. But when you use traits, you can simply declare the traits itself as a friend, so less boilerplate.
