### ISSUE TITLE
data should be required to return pointer/const_pointer

### ISSUE THREAD

**Issue by gnzlbg** [everard/contiguous-container#7]
Currently `contiguous_container::data()` returns `value_type*` and `const value_type*`, but it should probably just return `pointer`/`const_pointer` instead.

I think it would make more sense to require `Storage` to provide `.data()`, and implement `begin/end/...` in `contiguous_storage` as a function of it. IIUC the proposal, `being` and `end` are required to return `pointer`/`const_pointer`.

I also wonder whether `Storage::pointer` can be a fancy pointer or not (it is not clear to me from the proposal). I would say that `std::is_pointer_v<Storage::pointer> == true`, which means that `Storage::pointer` _must_ be a raw pointer type. In this case I wonder whether `Storage` needs to define `value_type`, `pointer`, and `const_pointer` type members, or whether they could be just deduced from `data()` in `contiguous_container` using:

```c++
template <typename Storage>
struct contiguous_container : Storage {
  using pointer = decltype(std::declval<Storage&>().data());
  using const_pointer = decltype(std::declval<Storage const&>().data());
  using value_type = std::remove_pointer_t<pointer>;

};
```

**Comment by everard** [comment]
No, everything is correct here. Please note that std::vector's data() returns raw pointer. Always.
And yes, pointer can be a "fancy" pointer. storage_traits works the same as allocator_traits in this regard.
If you are not defining pointer and const_pointer types in your Storage class, then by default they become raw pointers.

**Comment by gnzlbg** [comment]
>And yes, pointer can be a "fancy" pointer.

The next version of the proposal should probably clarify this.

**Comment by everard** [comment]
Why? Proposed wording isn't clear enough? it says in contiguous_container overview:

`using pointer = typename traits::pointer;`

And before that in storage_traits member types:
using pointer = see below;
Type : storage_type::pointer if the qualified-id storage_type::pointer is valid and denotes
a type (14.8.2); otherwise, value_type* .

**Comment by everard** [comment]
You mean, in design decisions section?

**Comment by gnzlbg** [comment]
Kind of. I guess that I wasn't sure because:

- the `Storage` concept is new to me,
- for all the useful `Storage` types I could conceive fancy pointers did not make sense,
- `using iterator = pointer` means that `pointer` must also model the `ContiguousIterator` concept, so the amount of fancy-ness that it could support is very limited. 
- `std::array::pointer` is always `T*` so it is fine for some containers to don't allow fancy pointers.

I guess a good example that justifies fancy pointers is the `dynamic_uninitialized_memory_buffer` templated by an `Allocator`. Fancy pointers are required to actually support this, since otherwise allocators with fancy pointers could not be supported. If you want to implement vector on top of `Storage`, you actually need this, since you would need to support the `Allocator`.
