### ISSUE TITLE
Rationale for public inheritance of Storage from contiguous_container

### ISSUE THREAD

**Issue by gnzlbg** [everard/contiguous-container#9]
I cannot find the rationale for `continuous_container` publicly inheriting from `Storage` in the paper, and I think such decision needs a good motivation, because otherwise `continuous_storage` re-exports everything that `Storage` has, but these are typically implementation details. 

For example: a user can slice a `continuous_storage<Storage>&` with `Storage&`, call the "unsafe" `size()` member (`Storage::size() -> size_type&`), and mutate the size of the `continuous_storage` without actually constructing or destructing elements, breaking all the container invariants. 

I don't think this can _easily_ happen by accident, but it opens the question of why isn't this forbidden by using private inheritance?

The cost would be that `contiguous_storage` would need to re-specify those functions of `Storage` that actually should be re-exported (e.g. `data`/`begin`...), but that would actually make the interface of `contiguous_storage` crystal clear, since it wouldn't depend on what `Storage` does or does not export anymore.

**Comment by everard** [comment]
And what if you want to extend contiguous_container by inheriting from it? If Storage is private base, then there is no way to access its data members, which in some cases might be desirable.

**Comment by gnzlbg** [comment]
In that case `protected` instead of `private` would work, and still prevent the situations I described above.

**Comment by everard** [comment]
And what if you want some other Storage's member functions be also usable? If you use protected, then everything public becomes protected.

**Comment by gnzlbg** [comment]
> And what if you want some other Storage's member functions be also usable?

Like?

**Comment by everard** [comment]
I don't know. Someone might come up with something, you never know.

**Comment by gnzlbg** [comment]
An alternative would be to add to `contiguous_container` a way to obtain a reference to the `Storage`, e.g., `auto get_storage() -> Storage&` (and a `const` overload). That way if you want the storage you can get it, but if we inherit privately (or protected) from it, one cannot get it by accident.

**Comment by everard** [comment]
yes, but still you'll have to write `c.get_storage().some_func()` instead of just `c.some_func()`

**Comment by gnzlbg** [comment]
But only for those funcs that are not part of the "vector-like" interface that `contiguous_container` exposes. 

I guess I would be better with publicly inheriting from `Storage` is `Storage::size` would not return a reference that can be mutated by accident by some other container class due to slicing. 

I think renaming it to `Storage::set_size(size_type& new_size)` instead would probably ease my concerns here, and also the ones about `Storage` classes not being able to `assert` some invariants on the sizes. I am not a big fan of accessors though.

**Comment by everard** [comment]
You can assert on size change, actually. You can define your type, which asserts on ++, --, +=, -=, and return it instead of integral.

I don't understand how you can accidentally corrupt your container through Storage, unless you explicitly convert it to base, in which case you know what you are doing.

**Comment by gnzlbg** [comment]
> You can define your type, which asserts on ++, --, +=, -=, and return it instead of integral.

At least for `difference_type` the standard requires it to be a signed integer type (it cannot be user defined), I would expect `size_type` to be defined similarly, but this is C++ (so I don't know). 

> I don't understand how you can accidentally corrupt your container through Storage, unless you explicitly convert it to base, in which case you know what you are doing.

```c++
void foo(MyStorage& a) { a.size() += 2; }
contiguous_container<MyStorage> a;
foo(a);
```
is what I had in mind.

**Comment by everard** [comment]
> At least for difference_type the standard requires it to be a signed integer type (it cannot be user defined), I would expect size_type to be defined similarly, but this is C++ (so I don't know).

Actually, Storage::size() does not return size_type. It returns reference to type with requirements from Table Y2 of the proposal. This type must be convertible to size_type, difference_type, also ++, --, +=, -= must be defined for it.

> ```
> void foo(MyStorage& a) { a.size() += 2; }
> contiguous_container<MyStorage> a;
> foo(a);
> ```
> 
> is what I had in mind.

Got it. So basically you know what you are doing, since you defined your Storage class :)

**Comment by everard** [comment]
Also why there are 4 functions instead of 2: once again, possible performance issues: set_size(get_size() + 1) vs ++

**Comment by gnzlbg** [comment]
The problem with "possible performance issues" is twofold. First, it can be used to justify writing everything in assembly, because it could theoretically be possible that a bug in the compiler introduces a performance regression. The second problem, is that if the performance differences are very small or not measurable, you could be targeting the niche of programmers that are actually going to be programming in assembly anyways and would never use your abstraction. 

Anyhow, to justify your performance concerns I think it should be enough to show that for 

```c++
void set_size(size_type n) {
  size_ = n;
}
```

the following two call sites generate different assembly:

```c++
set_size(1);
++size_;
```

For the `end()` being faster than `data() + size()` size case on an implementation that uses 3 pointers, you could try to show the same.

It is not that I don't believe your statement that these simplifications could introduce performance regressions, but rather that we are an API cost for it, and it would be nice to know what that actually buy us performance wise to know whether it is worth it or not.

**Comment by everard** [comment]
Ok, I understand. But you can't test it for all architectures. There is reason why someone uses pointer + size, and then GCC's and clangs's stdlibs use 3 pointers. Also you don't know what new architectures might appear in the future. The target audience of this is actually low-latency/embedded, so no, we can't rule out any possibility.

Also Standard does not mandate that set_size(get_size() + n) will become +=, so we can't be 100% sure.

I assume, that when you are implementing allocators, you not very often define construct/destroy. Same here: people who will use this will know better what to use. If they are fine with defaults, they will use defaults. I don't think that this is over-complication.

**Comment by gnzlbg** [comment]
As mentioned, try to measure where you can. You can use `gcc.godbolt.com` to compare the assembly of a couple of compilers and platforms.

> Also Standard does not mandate that set_size(get_size() + n) will become +=, so we can't be 100% sure.

This reasoning is a bit harmful, because the standard doesn't mandate that `+=` is faster than whatever `set_size(get_size() + n)` becomes. If you really need to be 100% sure, you need to write the assembly yourself, in which case you cannot use `contiguous_container` anyways.

The question is "How good is the code that _modern_ compilers actually generate?" 

The emphasis is on modern, because even though embedded platforms use older compilers, those compilers won't be able to use `contiguous_container` since it might require C++20 once it gets standardized. 

So if you are going to use performance as a justification for a more "customizable"/"large" API that is fine, just back it up with some test results from clang and gcc. 

If you made an assertion like that everybody is going to want to know "Which modern compiler doesn't optimize `data() + size() <=> end()` and why?" since that is something that should not happen in C++.

**Comment by everard** [comment]
Got it, I'll perform measurements :)
I guess you are right here. Optimizers get better and better at their job.

**Comment by everard** [comment]
Ok, I did just that and it seems that you are right.

1:
```
struct sz_test
{
  auto size() const noexcept
  {
    return size_;
  }

  void size(unsigned sz)
  {
    size_ = sz;
  }

  unsigned size_{};
};

int main()
{
  volatile unsigned sz0 = 5, sz1 = 8, sz2 = 15;
  sz_test s;
  s.size(sz0);
  s.size(s.size() + sz1);
  s.size(s.size() + sz2);

  return s.size();
}
```

2.
```
struct sz_test
{
  auto& size() noexcept
  {
    return size_;
  }

  unsigned size_{};
};

int main()
{
  volatile unsigned sz0 = 5, sz1 = 8, sz2 = 15;
  sz_test s;
  s.size() = sz0;
  s.size() += sz1;
  s.size() += sz2;

  return s.size();
}
```
3.

```
struct sz_test
{
  auto size() const noexcept
  {
    return end_ - beg_;
  }

  void size(unsigned sz)
  {
    end_ = beg_ + sz;
  }

  int data[16];
  int* beg_{data}, *end_{data};
};

int main()
{
  volatile unsigned sz0 = 5, sz1 = 8, sz2 = 15;
  sz_test s;
  s.size(sz0);
  s.size(s.size() + sz1);
  s.size(s.size() + sz2);

  return s.size();
}
```

and 4

```
struct sz_test
{
  auto& size() noexcept
  {
    return s_;
  }

  int data[16];
  struct sz
  {
        auto& operator+=(unsigned x) noexcept
        {
                end_ += x;
                return *this;
        }

        auto& operator=(unsigned x) noexcept
        {
                end_ = beg_ + x;
                return *this;
        }

        operator int() noexcept
        {
                return end_ - beg_;
        }

        int* beg_, *end_;
  } s_{data, data};
};

int main()
{
  volatile unsigned sz0 = 5, sz1 = 8, sz2 = 15;
  sz_test s;
  s.size() = sz0;
  s.size() += sz1;
  s.size() += sz2;

  return s.size();
}
```

all output the same assembly.
So regarding size, set_size you are correct, and I'm gonna make changes accordingly.

Regarding public inheritance, please see https://github.com/everard/contiguous-container/issues/10
Note that contiguous_container is not intended for use by beginners, this class is for experts, who know what they are doing. Also the intent is to further specify some standard Storage classes, which will implement various types of vector-like containers.

**Comment by gnzlbg** [comment]
`set_size` should be easier for the compiler to optimize than the `data() + size() == end()` transformations, I really wonder whether the compilers generate the same code in these cases as well. I don't have much time to try this, but I tried [this](https://godbolt.org/g/UY317C) in godbolt and it seems that at least clang and gcc can do the transformation (they optimize `data() + size() == end()` to `true` in both cases). The real test would be to do this with a vector class though.

**Comment by gnzlbg** [comment]
I tried doing the same with `std::vector` and it had the same effect. But I don't know whether clang uses libstdc++ or libc++ under godbolt, so it makes sense that if both are using the same standard library the same result is obtained.

**Comment by everard** [comment]
Clang's implementation also uses 3 pointers, though.

**Comment by everard** [comment]
Actually, we don't know how compiler will behave in real cases. Our tests are kinda synthetic.
size() and set_size are usually near each other, so I think optimizer will have no trouble there, but about end(), I think that if there is a certain amount of code between calls to end(), then in case of data + size it will perform pointer arithmetic for each such call. When calls to end() are near to each other, then optimizer will also have no trouble, I think. Same goes for full() and empty(). Because in case of two pointers, faster would be comparing beg_ and end_, in case of pointer + size, faster would be comparing with size, but when calls are next to each other, optimizer will just cache the previous result.

**Comment by everard** [comment]
Here: https://godbolt.org/g/8EAxMB
Note that code is different for end(), in case of data_ + size_, there is addition.

**Comment by gnzlbg** [comment]
> Note that code is different for end(), in case of data_ + size_, there is addition.

Indeed, I just tried on your example to do the opposite thing, that is, to only require `begin()`, `end()`, and compute `size` as `end() - begin()`, but depending on the implementation there is still a difference of one instruction being generated. Clang emits the same code as GCC here as well.

I don't know how important this is performance wise, but I think it can be definetely used to justify the decision of requiring begin(), end(), and size() in the design section of the proposal.

> Same goes for full() and empty()

I would guess so as well.

**Comment by everard** [comment]
Oh, by the way, are you OK with being a co-author of P0494? Since you are actively participating in design, I thought it would be appropriate.

P0494R0 is already sent to inclusion to the next mailing list, but R1 is not yet ready, so what do you think?
